# Generated by Django 4.2 on 2024-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='function',
        ),
        migrations.DeleteModel(
            name='MemberFunction',
        ),
        migrations.AddField(
            model_name='member',
            name='function',
            field=models.CharField(blank=True, choices=[('vocal principal', 'Vocal Principal'), ('backing vocal', 'Backing Vocal'), ('coral', 'Coral'), ('guitarra elétrica', 'Guitarra Elétrica'), ('baixo elétrico', 'Baixo Elétrico'), ('violão', 'Violão'), ('teclado', 'Teclado'), ('bateria', 'Bateria')], max_length=20, null=True),
        ),
    ]
