# Generated by Django 4.2 on 2024-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_member_function_delete_memberfunction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functions_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='function',
        ),
        migrations.AddField(
            model_name='member',
            name='function',
            field=models.ManyToManyField(to='accounts.memberfunctions'),
        ),
    ]
