# Generated by Django 4.2 on 2025-01-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberfunctions_remove_member_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
