# Generated by Django 4.2 on 2025-04-12 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['availability'], name='accounts_me_availab_e49c38_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='accounts_me_user_id_7cf4b8_idx'),
        ),
    ]
