# Generated by Django 4.2 on 2025-04-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_member_created_at_member_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberfunctions",
            old_name="functions_name",
            new_name="function_name",
        ),
    ]
