# Generated by Django 4.2 on 2025-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_functions_name_memberfunctions_function_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_picture/%Y/%m/%d/"
            ),
        ),
    ]
