# Generated by Django 4.2 on 2025-05-04 13:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_member_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberfunctions",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
