# Generated by Django 4.2 on 2025-05-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_member_function"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="memberfunctions",
            options={"ordering": ["function_name"]},
        ),
        migrations.RemoveField(
            model_name="member",
            name="profile_picture",
        ),
    ]
