services:
  db-praise-api:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  redis-praise-api:
    image: redis:latest
    container_name: redis-praise-api
    env_file:
      - .env
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "${PASSWORD_REDIS}"]
    volumes:
      - redis_data:/data
    restart: always
  
  # praise-api:
  #   build: .
  #   container_name: praise-api
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db-praise-api
  #     - redis-praise-api
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network

# networks:
#   app-network:
#     driver: bridge
#     name: network-praise

volumes:
  db_data:
  redis_data: