# Generated by Django 4.2 on 2024-12-22 11:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('music_tone', models.CharField(max_length=10)),
                ('music_chord', models.JSONField(max_length=10)),
                ('music_text', tinymce.models.HTMLField()),
                ('music_link', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_author', models.CharField(max_length=100)),
                ('version_title', models.CharField(max_length=100)),
                ('version_link', models.URLField(blank=True, max_length=255)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ManyToManyField(to='music.musiccategory'),
        ),
    ]
