# Generated by Django 4.2 on 2025-01-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_chord',
            field=models.CharField(max_length=50),
        ),
    ]
