# Generated by Django 4.2 on 2025-01-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_music_chord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicChord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_chord',
        ),
        migrations.AddField(
            model_name='music',
            name='music_chord',
            field=models.ManyToManyField(to='music.musicchord'),
        ),
    ]
