# Generated by Django 4.2 on 2025-04-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_playlist_music_version'),
        ('music', '0003_musicchord_remove_music_music_chord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicVersion',
        ),
    ]
