# Generated by Django 4.2 on 2025-04-12 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_delete_musicversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['music_title']},
        ),
        migrations.AddField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musicchord',
            name='chord_image',
            field=models.ImageField(blank=True, null=True, upload_to='chords/'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['music_title'], name='music_music_music_t_afeab8_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['author'], name='music_music_author_1c0ea3_idx'),
        ),
    ]
