# Generated by Django 4.2 on 2025-05-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_remove_musicchord_chord_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="category",
            field=models.ManyToManyField(blank=True, to="music.musiccategory"),
        ),
        migrations.AlterField(
            model_name="music",
            name="music_chord",
            field=models.ManyToManyField(blank=True, to="music.musicchord"),
        ),
    ]
