# Generated by Django 4.2 on 2024-12-22 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(blank=True, max_length=100)),
                ('playlist_date', models.DateField(default=datetime.date.today)),
                ('music', models.ManyToManyField(blank=True, to='music.music')),
                ('music_version', models.ManyToManyField(blank=True, to='music.musicversion')),
            ],
        ),
    ]
