# Generated by Django 4.2 on 2024-12-22 15:38

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraiseLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup_date', models.DateField(default=datetime.date.today)),
                ('lineup_event', models.CharField(blank=True, max_length=100)),
                ('backing_vocals', models.ManyToManyField(blank=True, related_name='lineup_backing_vocals', to='accounts.member')),
                ('choir', models.ManyToManyField(blank=True, related_name='lineup_choir', to='accounts.member')),
                ('drum_set', models.ManyToManyField(blank=True, related_name='lineup_drum_set', to='accounts.member')),
                ('electric_bass', models.ManyToManyField(blank=True, related_name='lineup_electric_bass', to='accounts.member')),
                ('electric_guitar', models.ManyToManyField(blank=True, related_name='lineup_electric_guitar', to='accounts.member')),
                ('guitar', models.ManyToManyField(blank=True, related_name='lineup_guitar', to='accounts.member')),
                ('lead_vocals', models.ManyToManyField(related_name='lineup_lead_vocals', to='accounts.member')),
                ('musical_keyboard', models.ManyToManyField(blank=True, related_name='lineup_musical_keyboard', to='accounts.member')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.playlist')),
            ],
        ),
    ]
