# Generated by Django 4.2 on 2025-04-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_availability'),
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praiselineup',
            name='backing_vocals',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='choir',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='drum_set',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='electric_bass',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='electric_guitar',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='guitar',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='lead_vocals',
        ),
        migrations.RemoveField(
            model_name='praiselineup',
            name='musical_keyboard',
        ),
        migrations.CreateModel(
            name='LineupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.memberfunctions')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lineup.praiselineup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'unique_together': {('lineup', 'member', 'function')},
            },
        ),
    ]
