# Generated by Django 4.2 on 2025-04-11 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0002_remove_praiselineup_backing_vocals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
