# Generated by Django 4.2 on 2025-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0003_lineupmember_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
