# Generated by Django 4.2 on 2025-04-12 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0004_lineupmember_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiselineup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praiselineup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
