# Generated by Django 4.2 on 2025-05-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_member_function"),
        ("lineup", "0005_praiselineup_created_at_praiselineup_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineupmember",
            name="function_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lineupmember",
            name="member_name_snapshot",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="lineupmember",
            name="function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.memberfunctions",
            ),
        ),
        migrations.AlterField(
            model_name="lineupmember",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.member",
            ),
        ),
    ]
