# Generated by Django 4.2 on 2025-05-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineup", "0006_lineupmember_function_name_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineupmember",
            options={"ordering": ["-lineup__lineup_date"]},
        ),
        migrations.AlterModelOptions(
            name="praiselineup",
            options={"ordering": ["-lineup_date"]},
        ),
    ]
